# Python Program for Floyd Warshall Algorithm

# Number of vertices in the graph
V = 60

# Define infinity as the large
# enough value. This value will be
# used for vertices not connected to each other
INF = 99999

# Solves all pair shortest path
# via Floyd Warshall Algorithm

def floydWarshall(graph):

	""" dist[][] will be the output
	matrix that will finally
		have the shortest distances
		between every pair of vertices """
	""" initializing the solution matrix
	same as input graph matrix
	OR we can say that the initial
	values of shortest distances
	are based on shortest paths considering no
	intermediate vertices """

	dist = list(map(lambda i: list(map(lambda j: j, i)), graph))

	""" Add all vertices one by one
	to the set of intermediate
	vertices.
	---> Before start of an iteration,
	we have shortest distances
	between all pairs of vertices
	such that the shortest
	distances consider only the
	vertices in the set
	{0, 1, 2, .. k-1} as intermediate vertices.
	----> After the end of a
	iteration, vertex no. k is
	added to the set of intermediate
	vertices and the
	set becomes {0, 1, 2, .. k}
	"""
	for k in range(V):

		# pick all vertices as source one by one
		for i in range(V):

			# Pick all vertices as destination for the
			# above picked source
			for j in range(V):

				# If vertex k is on the shortest path from
				# i to j, then update the value of dist[i][j]
				dist[i][j] = min(dist[i][j],
								dist[i][k] + dist[k][j]
								)
	printSolution(dist)


# A utility function to print the solution
def printSolution(dist):
	print ("Following matrix shows the shortest distances\
between every pair of vertices")
	for i in range(V):
		for j in range(V):
			if(dist[i][j] == INF):
				print ("%7s" % ("INF"),end=" ")
			else:
				print ("%7d\t" % (dist[i][j]),end=' ')
			if j == V-1:
				print ()


# Driver program to test the above program
# Let us create the following weighted graph
"""
			10
	(0)------->(3)
		|		 /|\
	5 |		 |
		|		 | 1
	\|/		 |
	(1)------->(2)
			3		 """
graph = [[float('Inf'), 12,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')] ,
[12,float('Inf'), 14, 22, 10,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')],
[float('Inf'), 14,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')],
[float('Inf'), 22,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'), 10,float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 18,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'), 1, 3,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 3,float('Inf'),float('Inf'), 4, 4, 7,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 7,float('Inf'),float('Inf'),float('Inf'), 4, 1, 10,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'), 4, 10, 13,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 10,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1, 6,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 10,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 13,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4, 8,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 6,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 8,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'), 18,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'), 11,float('Inf'),float('Inf'), 6,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 11,float('Inf'), 2, 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 6,float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'), 2, 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'), 5, 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2, 3,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 3,float('Inf'),float('Inf'), 1, 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1, 10,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'), 1, 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'), 13,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 10,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 13,float('Inf'),float('Inf'),float('Inf'),float('Inf'), 8, 1,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 8,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'), 15, 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 15,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'), 3, 6, 6,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 3,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 6,float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 6,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 2,float('Inf'),float('Inf'), 4, 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 4,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 5,float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1, 3,float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 1,float('Inf'),float('Inf'),float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 3,float('Inf'),float('Inf'), 3, 8], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 3,float('Inf'),float('Inf')], 
[float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'),float('Inf'), 8,float('Inf'),float('Inf')] 
]
# Print the solution
floydWarshall(graph)
# This code is contributed by Mythri J L
